---
title: "K-Means Attempt"
author: "Christian Pascual"
date: "3/12/2019"
output: html_document
---

```{r}
library(MASS)
library(tidyverse)
# Data generation
set.seed(123123)
Sigma = matrix(c(1, 0.5, 0.5, 1), 2, 2)
x1 = mvrnorm(n = 200, mu = c(0 ,0), Sigma)
Sigma = matrix(c(2,0.5,0.5,2),2,2)
x2 = mvrnorm(n = 200, mu = c(0, 5), Sigma)
Sigma = matrix(c(3,0.5,0.5,3),2,2)
x3 = mvrnorm(n = 200, mu = c(6 ,4), Sigma)
xx =  rbind(x1, x2, x3)

# Standardize the data
standardize = function(col) {
  mean = mean(col)
  stdev = sd(col)
  return((col - mean)/stdev)
}

data = as.tibble(xx) %>% map_df(.x = ., standardize)
```

We know from the data source that there are 600 points and 3 "true" centers. Therefore, the notation that we were given boils down to:

$$\mu = \{ \mu_1, \mu_2, \mu_3\}$$
The $r$ vector corresponds to the hard assignment. If the first dot was assigned to the first cluster, then $r$ would look like:
$$r_1 = ( r_{11}, r_{21}, r_{31} ) = (1, 0, 0)$$


```{r}
# something to calculate the objective function
calc.cluster.dist = function(point, clusters, assignments) {
  # Function to handle the inner loop
  
  # point is a row in the dataset
  # clusters is organized as an array of length 6
  # assignments is the hard assignments 
  # first two represent locations of first cluster... etc
  
  dist1 = assignments[1] * 
    sqrt((point$V1 - clusters[1])^2 + (point$V2 - clusters[2])^2)
  dist2 = assignments[2] * 
    sqrt((point$V1 - clusters[3])^2 + (point$V2 - clusters[4])^2)
  dist3 = assignments[3] * 
    sqrt((point$V1 - clusters[5])^2 + (point$V2 - clusters[6])^2)
  
  return(dist1 + dist2 + dist3)
}

# something to calculate the entire objective function
calc.obj = function(data, clusters, assignments) {
  total = 0
  for (i in 1:nrow(data)) {
    total = total + calc.cluster.dist(point = data[i,], 
                                      clusters = clusters,
                                      assignments = assignments)
  }
  return(total)
}

# calculate distances and assign a cluster
assign.cluster = function(point, clusters) {
  dist1 = sqrt((point$V1 - clusters[1])^2 + (point$V2 - clusters[2])^2)
  dist2 = sqrt((point$V1 - clusters[3])^2 + (point$V2 - clusters[4])^2)
  dist3 = sqrt((point$V1 - clusters[5])^2 + (point$V2 - clusters[6])^2)
  dists = c(dist1, dist2, dist3)
  min.dist = max(dists)
  r = ifelse(dists == min.dist, 1, 0)
  return(which(r == 1))
}

recalc.clusters = function(data, labels) {
  # Filter for the rows by the cluster they were assigned to
  label1.data = data[which(labels == 1),]
  label2.data = data[which(labels == 2),]
  label3.data = data[which(labels == 3),]
  
  return(c(
    cluster1.X = mean(label1.data$V1),
    cluster1.Y = mean(label1.data$V2),
    cluster2.X = mean(label2.data$V1),
    cluster2.Y = mean(label2.data$V2),
    cluster3.X = mean(label3.data$V1),
    cluster3.Y = mean(label3.data$V2)
  ))
}
```

```{r}
set.seed(14110)
### Initialize clusters randomly
# establish bounds of the standardized data
min.V1 = min(data$V1)
max.V1 = max(data$V1)
min.V2 = min(data$V2)
max.V2 = max(data$V2)

init.clusters = c(
  cluster1.X = runif(1, min.V1, max.V1),
  cluster1.Y = runif(1, min.V2, max.V2),
  cluster2.X = runif(1, min.V1, max.V1),
  cluster2.Y = runif(1, min.V2, max.V2),
  cluster3.X = runif(1, min.V1, max.V1),
  cluster3.Y = runif(1, min.V2, max.V2)
)

# Do we have acceptable starting points 
ggplot(data = data, aes(x = V1, y = V2)) + 
  geom_point() +
  geom_point(aes(x = init.clusters[1], y = init.clusters[2]), color = "red") + 
  geom_point(aes(x = init.clusters[3], y = init.clusters[4]), color = "blue") + 
  geom_point(aes(x = init.clusters[5], y = init.clusters[6]), color = "green")
```

```{r}
# welp here we go
maxiter = 14
i = 0
tol = 1e-5
clusters = init.clusters
cluster.path = NULL
diff.obj = Inf
old.obj = 0

# keep track of cluster paths
cluster.path = c(iter = 0, clusters)

while (i < maxiter) {
  i = i + 1
  label.vec = NULL
  for (j in 1:nrow(data)) {
    
    # Grab the point in the dataset
    point = data[j,]

    # Make the initial assignments and get labels
    label = assign.cluster(point = point, clusters = clusters)
    label.vec = c(label.vec, label) 

    # Now labels contains all of the group assignments
  }
  
  # must reassign clusters
  clusters = recalc.clusters(data = data, labels = label.vec)
  
  new.data = data %>% mutate(labels = factor(label.vec))
  
  # Add the clusters to the cluster tracker
  cluster.path = rbind(cluster.path, c(iter = i, clusters))
}

# Plot checks
ggplot(data = data, aes(x = V1, y = V2)) + 
  geom_point() +
  geom_point(aes(x = init.clusters[1], y = init.clusters[2]), color = "red") + 
  geom_point(aes(x = init.clusters[3], y = init.clusters[4]), color = "blue") + 
  geom_point(aes(x = init.clusters[5], y = init.clusters[6]), color = "green")

ggplot(data = data, aes(x = V1, y = V2)) + 
  geom_point() +
  geom_point(aes(x = clusters[1], y = clusters[2]), color = "red") + 
  geom_point(aes(x = clusters[3], y = clusters[4]), color = "blue") + 
  geom_point(aes(x = clusters[5], y = clusters[6]), color = "green")

ggplot(data = new.data, aes(x = V1, y = V2, color = labels)) + 
  geom_point() + theme(legend.position = "none")
```


